name: archive-templates
on: [workflow_dispatch]
jobs:
  package_current_template:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zip Vite Project
        working-directory: examples
        run: |
          [ -e ../templates/${TARGET_FILE}.zip ] || rm ../templates/${TARGET_FILE}.zip
          zip ../templates/${TARGET_FILE}.zip -r ${TARGET_PROJECT}/
        env:
          TARGET_FILE: typescript-vite-simple
          TARGET_PROJECT: typescript-vite-simple
      - name: Zip Create React App Project
        working-directory: examples
        run: |
          [ -e ../templates/${TARGET_FILE}.zip ] || rm ../templates/${TARGET_FILE}.zip
          zip ../templates/${TARGET_FILE}.zip -r ${TARGET_PROJECT}/
        env:
          TARGET_FILE: typescript-simple-react18
          TARGET_PROJECT: typescript-simple
      - name: Zip Create Matterport Project
        working-directory: examples
        run: |
          [ -e ../templates/${TARGET_FILE}.zip ] || rm ../templates/${TARGET_FILE}.zip
          zip ../templates/${TARGET_FILE}.zip -r ${TARGET_PROJECT}/
        env:
          TARGET_FILE: typescript-vite-matterport
          TARGET_PROJECT: typescript-vite-matterport
      - name: Push archives
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name PackageCurrentTemplate
          git config --global user.email PackageCurrentTemplate@system.com
          git add .
          git commit -m "commit from github actions package_current_template"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
